project:
  type: website
  output-dir: docs

website:
  title: "personal_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd

format:
  html:
    theme:
      - quartz
      - brand
    css: styles.css
    toc: true



